const lessonTitle = "太阳语";

const lessonData = [
    // ===== 第1段 =====
    ["我的", "wǒ de", "My", "Saya punya"],
    ["书房", "shū fáng", "study", "bilik bacaan"],
    ["处", "chù", "is located", "terletak"],
    ["在", "zài", "in", "di"],
    ["一个", "yí gè", "a", "sebuah"],
    ["大深坑里", "dà shēn kēng lǐ", "big deep pit", "lubang besar"],
    ["的", "de", "", ""],
    ["一排", "yì pái", "a row of", "deretan"],
    ["二层砖楼", "èr céng zhuān lóu", "two-storey brick building", "bangunan bata dua tingkat"],
    ["的", "de", "", ""],
    ["底层", "dǐ céng", "ground floor", "tingkat bawah"],
    ["中间", "zhōng jiān", "in the middle", "tengah"],
    ["。", "", "", ""],
    ["这排房子", "zhè pái fáng zi", "This row of houses", "Deretan rumah ini"],
    ["东西走向", "dōng xi zǒu xiàng", "east-west oriented", "berorientasi timur-barat"],
    ["，", "", "", ""],
    ["阴暗潮湿", "yīn àn cháo shī", "dark and damp", "gelap dan lembap"],
    ["，", "", "", ""],
    ["低层的居民", "dǐ céng de jū mín", "residents on the ground floor", "penghuni tingkat bawah"],
    ["多半", "duō bàn", "mostly", "kebanyakan"],
    ["都", "dōu", "all", "semua"],
    ["患上了", "huàn shàng le", "suffered from", "menghidap"],
    ["关节炎", "guān jié yán", "arthritis", "artritis"],
    ["。", "", "", ""],
    ["尤其是", "yóu qí shì", "Especially", "Terutamanya"],
    ["四周的", "sì zhōu de", "surrounding", "sekeliling"],
    ["楼房", "lóu fáng", "buildings", "bangunan"],
    ["冲天而起之后", "chōng tiān ér qǐ zhī hòu", "after shooting up into the sky", "selepas menjulang tinggi"],
    ["，", "", "", ""],
    ["这排房子", "zhè pái fáng zi", "this row of houses", "deretan rumah ini"],
    ["几乎", "jī hū", "almost", "hampir"],
    ["再也", "zài yě", "no longer", "tidak lagi"],
    ["见不到", "jiàn bú dào", "could not see", "tidak dapat melihat"],
    ["阳光了", "yáng guāng le", "sunlight", "cahaya matahari"],
    ["。", "", "", ""],
    ["这样", "zhè yàng", "This way", "Dengan ini"],
    ["倒", "dào", "actually", "sebaliknya"],
    ["也有个好处", "yě yǒu ge hǎo chù", "also had an advantage", "juga ada kebaikan"],
    ["：", "", "", ""],
    ["门庭冷落", "mén tíng lěng luò", "quiet and deserted", "sunyi sepi"],
    ["，", "", "", ""],
    ["安静自在", "ān jìng zì zài", "peaceful and free", "tenang dan selesa"],
    ["，", "", "", ""],
    ["是个", "shì ge", "is a", "ialah"],
    ["读书写作", "dú shū xiě zuò", "reading and writing", "membaca dan menulis"],
    ["的", "de", "", ""],
    ["绝佳境地", "jué jiā jìng dì", "perfect place", "tempat yang sesuai"],
    ["，", "", "", ""],
    ["只是", "zhǐ shì", "only", "cuma"],
    ["大白天", "dà bái tiān", "in broad daylight", "pada siang hari"],
    ["浪费些电而已", "làng fèi xiē diàn ér yǐ", "wasting some electricity", "membazir sedikit elektrik"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["早点过后", "zǎo diǎn guò hòu", "After breakfast", "Selepas sarapan"],
    ["，", "", "", ""],
    ["走进书房", "zǒu jìn shū fáng", "entering the study", "masuk ke bilik bacaan"],
    ["，", "", "", ""],
    ["读一读", "dú yì dú", "read", "membaca"],
    ["，", "", "", ""],
    ["写一写", "xiě yì xiě", "write", "menulis"],
    ["，", "", "", ""],
    ["自以为", "zì yǐ wéi", "I thought", "saya fikir"],
    ["没有比这", "méi yǒu bǐ zhè", "there is nothing more", "tiada yang lebih"],
    ["更快活的事了", "gèng kuài huo de shì le", "happy than this", "gembira daripada ini"],
    ["。", "", "", ""],
    ["累了乏了", "lèi le fá le", "tired", "letih"],
    ["，", "", "", ""],
    ["就喝口茶", "jiù hē kǒu chá", "drink some tea", "minum secawan teh"],
    ["，", "", "", ""],
    ["抬头看", "tái tóu kàn", "look up at", "mendongak melihat"],
    ["窗外的楼群", "chuāng wài de lóu qún", "buildings outside the window", "bangunan di luar tingkap"],
    ["，", "", "", ""],
    ["和那", "hé nà", "and that", "dan itu"],
    ["逼窄的", "bī zhǎi de", "narrow", "sempit"],
    ["一线天空", "yī xiàn tiān kōng", "sliver of sky", "selangit"],
    ["。", "", "", ""],
    ["一天早晨", "yì tiān zǎo chén", "One morning", "Suatu pagi"],
    ["，", "", "", ""],
    ["我正写到妙处", "wǒ zhèng xiě dào miào chù", "I was writing a brilliant part", "saya sedang menulis bahagian yang baik"],
    ["，", "", "", ""],
    ["窗纱忽然", "chuāng shā hū rán", "the window screen suddenly", "tirai tingkap tiba-tiba"],
    ["穿进", "chuān jìn", "let in", "masuk"],
    ["一束", "yí shù", "a beam of", "seberkas"],
    ["强烈的光芒", "qiáng liè de guāng máng", "strong light", "cahaya yang kuat"],
    ["，", "", "", ""],
    ["如探照灯般", "rú tàn zhào dēng bān", "like a searchlight", "seperti lampu carian"],
    ["绕来绕去", "rào lái rào qù", "moving around", "berpusing-pusing"],
    ["，", "", "", ""],
    ["把个宁静的斗室", "bǎ ge níng jìng de dǒu shì", "turning the quiet room", "menjadikan bilik yang sunyi"],
    ["弄得一片光明", "nòng de yí piàn guāng míng", "bright", "terang benderang"],
    ["，", "", "", ""],
    ["宛若", "wǎn ruò", "as if", "seolah-olah"],
    ["火光四溅的", "huǒ guāng sì jiàn de", "sparks flying", "percikan api"],
    ["铁匠炉子", "tiě jiàng lú zi", "blacksmith's furnace", "relau tukang besi"],
    ["。", "", "", ""],
    ["我刚站起来", "wǒ gāng zhàn qǐ lái", "I just stood up", "saya baru berdiri"],
    ["，", "", "", ""],
    ["那束阳光", "nà shù yáng guāng", "that beam of sunlight", "sinar matahari itu"],
    ["就钉住我的脸", "jiù dìng zhù wǒ de liǎn", "fixed on my face", "tertumpu pada muka saya"],
    ["，", "", "", ""],
    ["动也不动", "dòng yě bù dòng", "motionless", "tidak bergerak"],
    ["，", "", "", ""],
    ["使我", "shǐ wǒ", "making me", "membuatkan saya"],
    ["无法睁开眼睛", "wú fǎ zhēng kāi yǎn jīng", "unable to open my eyes", "tidak dapat membuka mata"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["有点气恼", "yǒu diǎn qì nǎo", "a bit annoyed", "agak marah"],
    ["，", "", "", ""],
    ["猛地举起拳头", "měng de jǔ qǐ quán tou", "suddenly raised my fist", "tiba-tiba mengangkat penumbuk"],
    ["，", "", "", ""],
    ["那束阳光", "nà shù yáng guāng", "that beam of sunlight", "sinar matahari itu"],
    ["一下子不见了", "yí xià zi bú jiàn le", "disappeared", "hilang sekelip mata"],
    ["。", "", "", ""],
    ["我睁开眼睛", "wǒ zhēng kāi yǎn jīng", "I opened my eyes", "saya membuka mata"],
    ["，", "", "", ""],
    ["却", "què", "but", "tetapi"],
    ["是一团黑洞", "shì yì tuán hēi dòng", "it was a dark void", "ia adalah lubang gelap"],
    ["。", "", "", ""],
    ["过了一阵子", "guò le yí zhèn zi", "After a while", "Selepas beberapa ketika"],
    ["才隐约发现", "cái yǐn yuē fā xiàn", "I faintly discovered", "baru samar-samar nampak"],
    ["，", "", "", ""],
    ["那是个孩子", "nà shì ge hái zi", "it was a child", "itu adalah seorang kanak-kanak"],
    ["，", "", "", ""],
    ["晃着小圆镜", "huàng zhe xiǎo yuán jìng", "waving a small round mirror", "melambai-lambai cermin bulat kecil"],
    ["，", "", "", ""],
    ["玩太阳呢", "wán tài yáng ne", "playing with the sun", "bermain dengan cahaya matahari"],
    ["。", "", "", ""],
    ["我不去计较", "wǒ bù qù jì jiào", "I didn't bother", "saya tidak peduli"],
    ["，", "", "", ""],
    ["坐下来", "zuò xià lái", "sat down", "duduk"],
    ["继续写作", "jì xù xiě zuò", "continued writing", "terus menulis"],
    ["。", "", "", ""],
    ["刚写了一句", "gāng xiě le yí jù", "just wrote a sentence", "baru menulis satu ayat"],
    ["，", "", "", ""],
    ["那束阳光", "nà shù yáng guāng", "that beam of sunlight", "sinar matahari itu"],
    ["又跑了进来", "yòu pǎo le jìn lái", "ran in again", "masuk lagi"],
    ["，", "", "", ""],
    ["在我的额上", "zài wǒ de é shàng", "on my forehead", "di dahi saya"],
    ["锯过来锯过去的", "jù guò lái jù guò qù de", "sawing back and forth", "bergerak ke sana ke mari"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    ["我愤怒了", "wǒ fèn nù le", "I got angry", "Saya marah"],
    ["，", "", "", ""],
    ["就起身出门", "jiù qǐ shēn chū mén", "got up and went out", "bangun dan keluar"],
    ["，", "", "", ""],
    ["快步上完", "kuài bù shàng wán", "quickly walked up", "cepat naik"],
    ["几十级台阶", "jǐ shí jí tái jiē", "dozens of steps", "beberapa puluh anak tangga"],
    ["。", "", "", ""],
    ["我要教训教训", "wǒ yào jiào xùn jiào xùn", "I wanted to teach a lesson", "saya mahu mengajar"],
    ["那个顽童", "nà ge wán tóng", "that naughty child", "budak nakal itu"],
    ["。", "", "", ""],
    ["然而", "rán ér", "However", "Namun"],
    ["，", "", "", ""],
    ["一见我来了", "yí jiàn wǒ lái le", "as soon as he saw me", "sebaik melihat saya datang"],
    ["，", "", "", ""],
    ["那孩子", "nà hái zi", "that child", "budak itu"],
    ["却", "què", "but", "tetapi"],
    ["一脸愉快的表情", "yì liǎn yú kuài de biǎo qíng", "had a happy expression", "raut muka gembira"],
    ["；", "", "", ""],
    ["而我也", "ér wǒ yě", "and I also", "dan saya juga"],
    ["不好发作的", "bù hǎo fā zuò de", "couldn't get angry", "tidak dapat marah"],
    ["，", "", "", ""],
    ["因为他是个瘫子", "yīn wèi tā shì ge tān zi", "because he was a crippled child", "kerana dia seorang lumpuh"],
    ["。", "", "", ""],
    ["我冲他笑了笑", "wǒ chōng tā xiào le xiào", "I smiled at him", "saya tersenyum kepadanya"],
    ["，", "", "", ""],
    ["依然回到书房", "yī rán huí dào shū fáng", "still returned to the study", "kembali ke bilik bacaan"],
    ["，", "", "", ""],
    ["写作起来", "xiě zuò qǐ lái", "continued writing", "meneruskan penulisan"],
    ["，", "", "", ""],
    ["以免灵感走失", "yǐ miǎn líng gǎn zǒu shī", "so as not to lose inspiration", "supaya inspirasi tidak hilang"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    ["可是", "kě shì", "But", "Tetapi"],
    ["，", "", "", ""],
    ["一连几天的早晨", "yī lián jǐ tiān de zǎo chén", "for several mornings in a row", "beberapa pagi berturut-turut"],
    ["，", "", "", ""],
    ["只要我", "zhǐ yào wǒ", "as long as I", "selagi saya"],
    ["一坐到书案前", "yí zuò dào shū àn qián", "sat at my desk", "duduk di meja tulis"],
    ["，", "", "", ""],
    ["那束阳光", "nà shù yáng guāng", "that beam of sunlight", "sinar matahari itu"],
    ["便跳跃进来", "biàn tiào yuè jìn lái", "would jump in", "akan melompat masuk"],
    ["，", "", "", ""],
    ["如小猫捕鼠", "rú xiǎo māo bǔ shǔ", "like a cat catching a mouse", "seperti kucing menangkap tikus"],
    ["，", "", "", ""],
    ["东闪西蹦", "dōng shǎn xī bèng", "darting here and there", "melompat ke sana ke mari"],
    ["。", "", "", ""],
    ["它虽无声响", "tā suī wú shēng xiǎng", "Although it made no sound", "Walaupun tiada bunyi"],
    ["，", "", "", ""],
    ["却有一种", "què yǒu yì zhǒng", "it had a kind of", "ia ada sejenis"],
    ["吵闹烦人", "chǎo nào fán rén", "annoying", "mengganggu"],
    ["的效果", "de xiào guǒ", "effect", "kesan"],
    ["。", "", "", ""],
    ["我想", "wǒ xiǎng", "I thought", "saya fikir"],
    ["我应该", "wǒ yīng gāi", "I should", "saya patut"],
    ["跟孩子谈谈", "gēn hái zi tán tan", "talk to the child", "bercakap dengan budak itu"],
    ["：", "", "", ""],
    ["有意打扰", "yǒu yì dǎ rǎo", "deliberately disturbing", "sengaja mengganggu"],
    ["别人的工作", "bié rén de gōng zuò", "others' work", "kerja orang lain"],
    ["是不礼貌的", "shì bù lǐ mào de", "is impolite", "adalah tidak sopan"],
    ["，", "", "", ""],
    ["缺乏教养的", "quē fá jiào yǎng de", "lacking upbringing", "kurang ajar"],
    ["。", "", "", ""],
    ["我知道", "wǒ zhī dào", "I knew", "saya tahu"],
    ["这个不幸的孩子", "zhè ge bù xìng de hái zi", "this unfortunate child", "budak malang ini"],
    ["，", "", "", ""],
    ["父母只管", "fù mǔ zhǐ guǎn", "his parents only took care of", "ibu bapa hanya menjaga"],
    ["他的吃穿睡", "tā de chī chuān shuì", "his food, clothing and sleep", "makan, pakaian dan tidurnya"],
    ["，", "", "", ""],
    ["其余就不过问了", "qí yú jiù bù guò wèn le", "and didn't care about the rest", "selebihnya tidak dipedulikan"],
    ["；", "", "", ""],
    ["他们上班时", "tā men shàng bān shí", "when they went to work", "ketika mereka bekerja"],
    ["，", "", "", ""],
    ["就把轮椅", "jiù bǎ lún yǐ", "they would push the wheelchair", "mereka akan tolak kerusi roda"],
    ["推到门外", "tuī dào mén wài", "outside the door", "ke luar pintu"],
    ["，", "", "", ""],
    ["让孩子晒太阳", "ràng hái zi shài tài yáng", "let the child sunbathe", "biarkan budak itu berjemur"],
    ["，", "", "", ""],
    ["看楼房", "kàn lóu fáng", "look at the buildings", "melihat bangunan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    ["“", "", "", ""],
    ["瓦片", "wǎ piàn", "Tile", "Wapian"],
    ["，”", "", "", ""],
    ["我叫着", "wǒ jiào zhe", "I called", "saya panggil"],
    ["孩子的名字", "hái zi de míng zi", "the child's name", "nama budak itu"],
    ["。", "", "", ""],
    ["“", "", "", ""],
    ["你干吗", "nǐ gàn má", "Why do you", "Kenapa awak"],
    ["要往我房间里", "yào wǎng wǒ fáng jiān lǐ", "shine sunlight", "menyinarkan cahaya"],
    ["照太阳呢", "zhào tài yáng ne", "into my room", "ke dalam bilik saya"],
    ["？”", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    ["“", "", "", ""],
    ["我跟你说话呀", "wǒ gēn nǐ shuō huà ya", "I'm talking to you", "Saya bercakap dengan awak"],
    ["，", "", "", ""],
    ["叔叔", "shū shu", "uncle", "pakcik"],
    ["。”", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["惊讶不已", "jīng yà bù yǐ", "very surprised", "sangat terkejut"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    ["“", "", "", ""],
    ["我天天看你", "wǒ tiān tiān kàn nǐ", "I watch you every day", "Saya lihat awak setiap hari"],
    ["，", "", "", ""],
    ["好长好长时间了", "hǎo cháng hǎo cháng shí jiān le", "for a very long time", "sudah lama"],
    ["。", "", "", ""],
    ["人家都是", "rén jiā dōu shì", "Other people are all", "Orang lain semua"],
    ["一伙一伙地", "yī huǒ yī huǒ de", "in groups", "secara berkumpulan"],
    ["上班去了", "shàng bān qù le", "going to work", "pergi bekerja"],
    ["，", "", "", ""],
    ["只有你", "zhǐ yǒu nǐ", "only you", "hanya awak"],
    ["是一个人", "shì yí gè rén", "are alone", "seorang diri"],
    ["，", "", "", ""],
    ["在黑房子里", "zài hēi fáng zi lǐ", "in the dark room", "di dalam bilik gelap"],
    ["。", "", "", ""],
    ["我天天看你的头", "wǒ tiān tiān kàn nǐ de tóu", "I watch your head every day", "Saya lihat kepala awak setiap hari"],
    ["，", "", "", ""],
    ["头低着", "tóu dī zhe", "head lowered", "kepala menunduk"],
    ["——", "", "", ""],
    ["你在里边哭吧", "nǐ zài lǐ biān kū ba", "are you crying inside", "awak menangis di dalam"],
    ["？", "", "", ""],
    ["可怜的", "kě lián de", "Poor", "Kasihan"],
    ["，", "", "", ""],
    ["又没人和你说话", "yòu méi rén hé nǐ shuō huà", "no one to talk to you", "tiada orang bercakap dengan awak"],
    ["。", "", "", ""],
    ["我让妈妈", "wǒ ràng mā ma", "I asked mom", "Saya minta ibu"],
    ["给我买个小镜子", "gěi wǒ mǎi ge xiǎo jìng zi", "to buy me a small mirror", "belikan saya cermin kecil"],
    ["，", "", "", ""],
    ["她说", "tā shuō", "she said", "dia berkata"],
    ["：", "", "", ""],
    ["‘", "", "", ""],
    ["男孩照镜子", "nán hái zhào jìng zi", "Boys looking in mirrors", "Lelaki bercermin"],
    ["，", "", "", ""],
    ["多丢人", "duō diū rén", "so embarrassing", "memalukan"],
    ["！", "", "", ""],
    ["’", "", "", ""],
    ["爷爷从乡下来了", "yé ye cóng xiāng xià lái le", "Grandpa came from the countryside", "Datuk datang dari kampung"],
    ["，", "", "", ""],
    ["我才请他", "wǒ cái qǐng tā", "I asked him", "saya baru minta dia"],
    ["给我买了一个……", "gěi wǒ mǎi le yí gè……", "to buy me one", "belikan saya satu..."],
    ["叔叔", "shū shu", "uncle", "pakcik"],
    ["，", "", "", ""],
    ["你干吗哭呢", "nǐ gàn má kū ne", "why are you crying", "kenapa awak menangis"],
    ["？", "", "", ""],
    ["你别哭呀", "nǐ bié kū ya", "don't cry", "jangan menangis"],
    ["，", "", "", ""],
    ["只要出太阳", "zhǐ yào chū tài yáng", "as long as the sun comes out", "asalkan ada matahari"],
    ["，", "", "", ""],
    ["我天天早上", "wǒ tiān tiān zǎo shàng", "every morning", "setiap pagi"],
    ["都给你说话", "dōu gěi nǐ shuō huà", "I'll talk to you", "saya akan bercakap dengan awak"],
    ["，", "", "", ""],
    ["你不会急死的", "nǐ bú huì jí sǐ de", "you won't die of loneliness", "awak tidak akan mati kesunyian"],
    ["……”", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    ["这", "zhè", "This", "Ini"],
    ["是", "shì", "was", "ialah"],
    ["我生平", "wǒ shēng píng", "in my life", "dalam hidup saya"],
    ["第一次", "dì yī cì", "the first time", "kali pertama"],
    ["知道了", "zhī dào le", "knew", "tahu"],
    ["阳光", "yáng guāng", "sunlight", "cahaya matahari"],
    ["还有一种", "hái yǒu yì zhǒng", "also had a kind of", "juga mempunyai sejenis"],
    ["语言功能", "yǔ yán gōng néng", "language function", "fungsi bahasa"],
    ["。", "", "", ""],
    ["而", "ér", "And", "Dan"],
    ["告诉我", "gào su wǒ", "who told me", "yang memberitahu saya"],
    ["这一知识的", "zhè yī zhī shi de", "this knowledge", "pengetahuan ini"],
    ["，", "", "", ""],
    ["竟", "jìng", "unexpectedly", "rupanya"],
    ["是一个", "shì yí gè", "was a", "ialah seorang"],
    ["下肢瘫痪", "xià zhī tān huàn", "lower limb paralysis", "lumpuh kaki"],
    ["且", "qiě", "and", "dan"],
    ["一字不识", "yī zì bù shí", "completely illiterate", "buta huruf"],
    ["的", "de", "", ""],
    ["八岁男孩", "bā suì nán hái", "eight-year-old boy", "budak lelaki lapan tahun"],
    ["！", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["深感", "shēn gǎn", "deeply felt", "sangat merasa"],
    ["羞愧和渺小", "xiū kuì hé miǎo xiǎo", "ashamed and insignificant", "malu dan rendah diri"],
    ["，", "", "", ""],
    ["就发愤学习", "jiù fā fèn xué xí", "and studied diligently", "lalu belajar dengan tekun"],
    ["，", "", "", ""],
    ["不耻下问", "bù chǐ xià wèn", "not ashamed to ask", "tidak malu bertanya"],
    ["。", "", "", ""],
    ["在那束", "zài nà shù", "In that beam of", "Dalam sinar"],
    ["每天早晨降临的", "měi tiān zǎo chén jiàng lín de", "daily morning", "yang datang setiap pagi"],
    ["，", "", "", ""],
    ["时断时续的", "shí duàn shí xù de", "intermittent", "kadang-kadang"],
    ["阳光的陪伴下", "yáng guāng de péi bàn xià", "sunlight's company", "teman cahaya matahari"],
    ["，", "", "", ""],
    ["我慢慢领悟了", "wǒ màn màn lǐng wù le", "I gradually understood", "saya perlahan-lahan memahami"],
    ["人类的美好", "rén lèi de měi hǎo", "the goodness of humanity", "kebaikan manusia"],
    ["，", "", "", ""],
    ["和人类的渴望", "hé rén lèi de kě wàng", "and human longing", "dan keinginan manusia"],
    ["。", "", "", ""],
    ["终于", "zhōng yú", "Finally", "Akhirnya"],
    ["，", "", "", ""],
    ["我的", "wǒ de", "my", "saya punya"],
    ["一部作品", "yī bù zuò pǐn", "a work", "sebuah karya"],
    ["引起了", "yǐn qǐ le", "aroused", "menimbulkan"],
    ["广泛的共鸣", "guǎng fàn de gòng míng", "wide resonance", "resonans yang luas"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    ["那天清晨", "nà tiān qīng chén", "That morning", "Pagi itu"],
    ["，", "", "", ""],
    ["电视台", "diàn shì tái", "The TV station", "Stesen televisyen"],
    ["来了两个人", "lái le liǎng ge rén", "two people came", "datang dua orang"],
    ["采访我", "cǎi fǎng wǒ", "interview me", "menemubual saya"],
    ["，", "", "", ""],
    ["问我是", "wèn wǒ shì", "asking how I", "bertanya bagaimana saya"],
    ["怎么成功的", "zěn me chéng gōng de", "succeeded", "berjaya"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["走", "zǒu", "Come", "Pergi"],
    ["，", "", "", ""],
    ["到我的书房后", "dào wǒ de shū fáng hòu", "to my study", "ke bilik bacaan saya"],
    ["，", "", "", ""],
    ["你们就明白了", "nǐ men jiù míng bái le", "and you'll understand", "kamu akan faham"],
    ["。”", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["领着客人", "lǐng zhe kè rén", "led the guests", "membawa tetamu"],
    ["下到", "xià dào", "down to", "turun ke"],
    ["我那", "wǒ nà", "my", "saya punya"],
    ["霉而黑的房间", "méi ér hēi de fáng jiān", "mouldy and dark room", "bilik yang berbau dan gelap"],
    ["。", "", "", ""],
    ["然后", "rán hòu", "Then", "Kemudian"],
    ["，", "", "", ""],
    ["我坐到书案前", "wǒ zuò dào shū àn qián", "I sat at my desk", "saya duduk di meja tulis"],
    ["，", "", "", ""],
    ["请他们安静", "qǐng tā men ān jìng", "asked them to be quiet", "minta mereka diam"],
    ["，", "", "", ""],
    ["安静地观赏", "ān jìng de guān shǎng", "and quietly watch", "dan tenang memerhati"],
    ["那束定时出现的阳光", "nà shù dìng shí chū xiàn de yáng guāng", "that punctual beam of sunlight", "sinar matahari yang muncul tepat pada masanya"],
    ["。", "", "", ""],
    ["可是", "kě shì", "But", "Tetapi"],
    ["，", "", "", ""],
    ["十几分钟过去了", "shí jǐ fēn zhōng guò qù le", "more than ten minutes passed", "lebih sepuluh minit berlalu"],
    ["，", "", "", ""],
    ["却没一点动静", "què méi yì diǎn dòng jìng", "but there was no movement", "tetapi tiada sebarang pergerakan"],
    ["。", "", "", ""],
    ["我忍不住了", "wǒ rěn bú zhù le", "I couldn't help it", "saya tidak tahan"],
    ["，", "", "", ""],
    ["就跑出去找那孩子", "jiù pǎo chū qù zhǎo nà hái zi", "ran out to find the child", "lalu berlari keluar mencari budak itu"],
    ["。", "", "", ""],
    ["只见他手里", "zhǐ jiàn tā shǒu lǐ", "I saw in his hand", "saya lihat di tangannya"],
    ["拿着小圆镜", "ná zhe xiǎo yuán jìng", "holding the small round mirror", "memegang cermin bulat kecil"],
    ["，", "", "", ""],
    ["所不同的是", "suǒ bù tóng de shì", "the difference was", "yang berbeza ialah"],
    ["，", "", "", ""],
    ["小圆镜", "xiǎo yuán jìng", "the small round mirror", "cermin bulat kecil itu"],
    ["被一块白手绢", "bèi yí kuài bái shǒu juàn", "was wrapped in a white handkerchief", "dibalut dengan sapu tangan putih"],
    ["包得严严的", "bāo de yán yán de", "tightly wrapped", "dibalut dengan rapat"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    ["“", "", "", ""],
    ["瓦片", "wǎ piàn", "Tile", "Wapian"],
    ["，", "", "", ""],
    ["你今天干吗", "nǐ jīn tiān gàn má", "Why didn't you", "Kenapa awak hari ini"],
    ["不跟我‘说话’呀", "bù gēn wǒ ‘shuō huà’ ya", "talk to me today", "tidak bercakap dengan saya"],
    ["？”", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    ["“", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["，", "", "", ""],
    ["我今天", "wǒ jīn tiān", "today", "hari ini"],
    ["，”", "", "", ""],
    ["孩子露出", "hái zi lù chū", "the child showed", "budak itu menunjukkan"],
    ["灿烂而幸福的微笑", "càn làn ér xìng fú de wēi xiào", "a brilliant and happy smile", "senyuman yang cerah dan gembira"],
    ["。", "", "", ""],
    ["“", "", "", ""],
    ["今天有他们", "jīn tiān yǒu tā men", "Today there are them", "Hari ini ada mereka"],
    ["跟你说话", "gēn nǐ shuō huà", "talking to you", "bercakap dengan awak"],
    ["，", "", "", ""],
    ["我就用不着", "wǒ jiù yòng bù zháo", "so I don't need to", "jadi saya tidak perlu"],
    ["照太阳啦", "zhào tài yáng la", "shine the sun", "menyinarkan matahari"],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第12段

    ["身后的记者", "shēn hòu de jì zhě", "The reporters behind me", "Wartawan di belakang"],
    ["早将这一切", "zǎo jiāng zhè yī qiè", "had already recorded all this", "telah merakamkan semua ini"],
    ["录入镜头", "lù rù jìng tóu", "into the camera", "ke dalam kamera"],
    ["，", "", "", ""],
    ["而我", "ér wǒ", "but I", "tetapi saya"],
    ["却丝毫没有感觉", "què sī háo méi yǒu gǎn jué", "didn't feel it at all", "langsung tidak sedar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["方英文", "fāng yīng wén", "Fang Yingwen", "Fang Yingwen"],
    ["《", "", "", ""],
    ["太阳语", "tài yáng yǔ", "Sunlight Language", "Bahasa Cahaya Matahari"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
